AC_INIT(Yambo, 5.1.0 r.20568 h.cc361dcb7, yambo@yambo-code.org)
SVERSION="5"
SSUBVERSION="1"
SPATCHLEVEL="0"
SREVISION="20568"
SHASH="cc361dcb7"
AC_SUBST(SVERSION)
AC_SUBST(SSUBVERSION)
AC_SUBST(SPATCHLEVEL)
AC_SUBST(SREVISION)
AC_SUBST(SHASH)
