name: Build with EESSI
on:
  push:
    branches:
      - tech-ci

jobs:
  ubuntu-minimal:
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-24.04
    #strategy:
    #  matrix:
    #    os:
    #      - ubuntu-24.04-arm
    #      - ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: eessi/github-action-eessi@v3
    - name: Build dependencies via EESSI-extend
      run: |
        module load EESSI-extend
        unset EASYBUILD_DEBUG
        cd easybuild
        eb --logtostdout -r PETSc-3.22.5-gompi-2023a-single-fb.eb
        eb --logtostdout -r SLEPc-3.22.2-gompi-2023a-single-fb.eb
        eb --logtostdout -r DeviceXlib-0.9.0-GCC-12.3.0-fb.eb
    - name: Build Yambo via EESSI-extend
      run: |
        module load EESSI-extend
        unset EASYBUILD_DEBUG
        cd easybuild
        eb --logtostdout -r --software-commit=$GITHUB_SHA Yambo-devel-foss-2023a.eb
      shell: bash
