name: CI with EESSI
on:
  push:
    branches:
      - tech-ci


env:
  EESSI_ENV: |
    source /cvmfs/software.eessi.io/versions/2023.06/init/lmod/bash
    export EESSI_USER_INSTALL=/scratch/nspallan/eessi
    module load EESSI-extend
    module load EasyBuild
    unset EASYBUILD_DEBUG


jobs:

  piazzagrande:
    if: contains(join(toJson(github.event.commits.*.message)), '[ci]')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build Yambo via EESSI-extend
        shell: bash -l {0}
        run: |
          ${{ env.EESSI_ENV }}
          cd easybuild
          eb --logtostdout --software-commit=$GITHUB_SHA Yambo-devel-foss-2023a.eb

      - name: Run Yambo-tester
        shell: bash -l {0}
        run: |
          ${{ env.EESSI_ENV }}
          module load Yambo/devel-foss-2023a-$GITHUB_SHA
          cd /scratch/nspallan
          source yambo-tester/.venv/bin/activate
          yambo-tester --scratch ci_runs --label devel-foss-2023a-$GITHUB_SHA --logger ci_runs/devel-foss-2023a-${GITHUB_SHA}.log


  ubuntu-minimal:
    if: contains(join(toJson(github.event.commits.*.message)), '[mini-ci]')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: eessi/github-action-eessi@v3

    #- name: Install wget
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y wget
    #
    #- name: Set up Python 3.12
    #  uses: actions/setup-python@v5
    #  with:
    #    python-version: '3.12'

    - name: Build Yambo (and some dependencies) via EESSI-extend
      shell: bash -l {0}
      run: |
        module load EESSI-extend
        unset EASYBUILD_DEBUG
        cd easybuild
        #eb --logtostdout -r PETSc-3.22.5-gompi-2023a-single-fb.eb
        #eb --logtostdout -r SLEPc-3.22.2-gompi-2023a-single-fb.eb
        eb --logtostdout -r DeviceXlib-0.9.0-GCC-12.3.0-fb.eb
        eb --logtostdout --software-commit=$GITHUB_SHA Yambo-devel-foss-2023a.eb

    - name: Run Yambo-tester
      shell: bash -l {0}
      run: |
        module load EESSI-extend
        module load Yambo/devel-foss-2023a-$GITHUB_SHA
        git clone https://github.com/yambo-code/yambo-tester.git
        cd yambo-tester
        git checkout toml
        python3 -m pip install .
        cd ..
        yambo-tester --scratch ci_runs --label devel-foss-2023a-$GITHUB_SHA
