name: CI with EESSI
on:
  push:
    branches:
      - tech-ci

jobs:
  ubuntu-minimal:
    if: contains(toLower(github.event.head_commit.message), '[ci')
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v4

      - name: Build Yambo via EESSI-extend
        shell: bash -l {0}
        run: |
          module load EESSI-extend
          module load EasyBuild
          unset EASYBUILD_DEBUG
          cd easybuild
          eb --logtostdout -r --software-commit=$GITHUB_SHA Yambo-devel-foss-2023a.eb

      - name: Run Yambo-tester
        shell: bash -l {0}
        run: |
          module load EESSI-extend
          module load EasyBuild
          module load Yambo/devel-foss-2023a-$GITHUB_SHA
          cd ${SCRATCH}
          source yambo-tester/.venv/bin/activate
          yambo-tester -scratch ci_runs -label foss-2023a-$GITHUB_SHA
