name: "FORD Documentation"

on:
  push:
    branches:
      - tech-doc

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup fortran
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: "gcc"
        version: 13

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r doc/requirements.txt

    - name: Render the doc
      run: |
        ford --output_dir docs docs.md
        cp doc/*.png docs/media/.

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/tech-doc'
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        force_orphan: true
